service: iac-cloud-sls
frameworkVersion: '2 || 3'

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  lambdaHashingVersion: '20201221'

package:
  individually: true
  exclude:
    - ./**

plugins:
  - serverless-webpack
  # - serverless-python-requirements

custom:
  webpack:
    packager: npm
#   pythonRequirements:
#     dockerizePip: non-linux
#     zip: true

functions:
  helloWorldJS:
    runtime: nodejs14.x
    handler: src/aws/lambda/hello-world/HelloWorld.handler
    events:
      - httpApi:
          path: /hello-world-js
          method: GET

  helloWorldPython:
    runtime: python3.8
    handler: src/aws/lambda/hello-world/HelloWorld.handler
    package:
      include:
        - src/aws/lambda/hello-world/HelloWorld.py
    events:
      - httpApi:
          path: /hello-world-python
          method: GET
