service: iac-cloud-sls
frameworkVersion: '2 || 3'

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  lambdaHashingVersion: '20201221'

package:
  individually: true
  exclude:
    - ./**

plugins:
  - serverless-webpack
  - serverless-python-requirements

custom:
  webpack:
    packager: npm
    excludeFiles: '**/*.py'
  pythonRequirements:
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.8
    layer:
      name: ${self:service}-${self:provider.stage}-python-layer
      description: Python requirements lambda layer
      compatibleRuntimes:
        - python3.8
      allowedAccounts:
        - '*'

functions:
  helloWorldJavascript:
    runtime: nodejs14.x
    handler: src/aws/lambda/javascript/HelloWorld.handler
    events:
      - httpApi:
          path: /hello-world-js
          method: GET

  helloWorldPython:
    runtime: python3.8
    handler: src/aws/lambda/python/HelloWorld.handler
    package:
      include:
        - src/aws/lambda/python/HelloWorld.py
    events:
      - httpApi:
          path: /hello-world-python
          method: GET

  coinRankingPython:
    runtime: python3.8
    handler: src/aws/lambda/python/CoinRanking.handler
    package:
      include:
        - src/aws/lambda/python/CoinRanking.py
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /coin-ranking-python
          method: GET
